version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - firebase

  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    volumes:
      - .:/firebase
      - ~/.firebase:/root/.firebase
    ports:
      - "4000:4000"
      - "8085:8085"
      - "9099:9099"