[build]
  command = "npm run build"
  functions = "dist"

[build.environment]
  FIREBASE_PROJECT = "lansing-codes-staging"

[context.firebase.environment]
  FIREBASE_PROJECT = "lansing-codes-staging"

[context.production.environment]
  FIREBASE_PROJECT = "lansing-codes"
