[build]
  command = "npm run build"
  functions = "dist"

[build.environment]
  FIREBASE_PROJECT = "staging"

[context.firebase.environment]
  FIREBASE_PROJECT = "staging"

[context.production.environment]
  FIREBASE_PROJECT = "production"
