[build]
  command = "npm run build"
  functions = "dist"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"
  FIREBASE_PROJECT = "staging"

[context.firebase.environment]
  FIREBASE_PROJECT = "staging"

[context.production.environment]
  FIREBASE_PROJECT = "production"
