[build]
  command = "npm run deploy"
  functions = "dist"

[build.environment]
  FIREBASE_PROJECT = "lansingcodes-dev"

[context.firebase.environment]
  FIREBASE_PROJECT = "lansing-codes-staging"

[context.master.environment]
  FIREBASE_PROJECT = "lansing-codes-staging"

[context.production.environment]
  FIREBASE_PROJECT = "lansing-codes"
